name: pbrx_rugby_app
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  smooth_page_indicator: ^1.1.0
  flutter_multi_select_items: ^0.4.3
  multi_dropdown: ^3.0.1
  path_provider: ^2.1.5
  intl: ^0.18.1
  http: ^0.13.5
  flutter: 
    sdk: flutter
  

  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/testJsonFiles/
  - assets/testJsonFiles/training_plan_1.json
  - assets/testJsonFiles/training_plan_2.json
  - assets/testJsonFiles/training_plan_3.json